configfile: "/mnt/e/xoo-genomics-analysis/config/config.yaml"

SAMPLES = config["pacbio_samples"]
FASTQ_DIR = config["fastq_dir"]
GENOME_SIZE = config["genome_size"]
TARGET_COV = config["target_coverage"]
THREADS = config["threads"]
MAPPING = config["illumina_mapping"]

rule all:
    input:
        expand("results/{sample}/{sample}_busco_report/short_summary.txt", sample=SAMPLES),
        expand("results/{sample}/spades_assembly/assembly.fasta", sample=SAMPLES)

rule estimate_coverage:
    input: fq = f"{FASTQ_DIR}/{{sample}}.fastq.gz"
    output: "results/qc/{sample}_bases.txt"
    shell: "zcat {input.fq} | awk 'NR%4==2 {{sum+=length($0)}} END {{print sum}}' > {output}"

rule downsample:
    input:
        fq = f"{FASTQ_DIR}/{{sample}}.fastq.gz",
        bases = "results/qc/{sample}_bases.txt"
    output: "results/downsampled/{sample}.fastq.gz"
    run:
        with open(input.bases) as f:
            total_bases = int(f.read().strip())
        current_cov = total_bases / GENOME_SIZE
        fraction = min(1.0, TARGET_COV / current_cov)
        shell(f"seqtk sample -s100 {input.fq} {fraction} | gzip > {output}")

rule flye:
    input: "results/downsampled/{sample}.fastq.gz"
    output: "results/assembly/{sample}/assembly.fasta"
    threads: THREADS
    shell:
        """
        flye --pacbio-raw {input} --out-dir results/assembly/{wildcards.sample} \
             --genome-size 5m --threads {threads}
        """

rule racon_round1:
    input:
        ref = "results/assembly/{sample}/assembly.fasta",
        reads = "results/downsampled/{sample}.fastq.gz"
    output: "results/{sample}/racon/racon1.fasta"
    threads: THREADS
    shell:
        """
        minimap2 -x map-pb -t {threads} {input.ref} {input.reads} > {wildcards.sample}_r1.paf
        racon -t {threads} {input.reads} {wildcards.sample}_r1.paf {input.ref} > {output}
        rm {wildcards.sample}_r1.paf
        """

rule pilon_polish:
    input:
        ref = "results/{sample}/racon/racon1.fasta",
        r1 = lambda w: f"{FASTQ_DIR}/{MAPPING[w.sample]}_1.fq.gz",
        r2 = lambda w: f"{FASTQ_DIR}/{MAPPING[w.sample]}_2.fq.gz"
    output: "results/{sample}/{sample}_final_polished.fasta"
    threads: THREADS
    shell:
        """
        bwa index {input.ref}
        bwa mem -t {threads} {input.ref} {input.r1} {input.r2} | \
        samtools view -u - | samtools sort -@ 4 -o {wildcards.sample}_tmp.bam
        samtools index {wildcards.sample}_tmp.bam
        pilon --genome {input.ref} --frags {wildcards.sample}_tmp.bam \
              --output {wildcards.sample}_final_polished --outdir results/{wildcards.sample} --fix all
        rm {wildcards.sample}_tmp.bam {wildcards.sample}_tmp.bam.bai
        """

rule spades:
    input:
        r1 = lambda w: f"{FASTQ_DIR}/{MAPPING[w.sample]}_1.fq.gz",
        r2 = lambda w: f"{FASTQ_DIR}/{MAPPING[w.sample]}_2.fq.gz"
    output: "results/{sample}/spades_assembly/assembly.fasta"
    threads: THREADS
    shell: "spades.py -1 {input.r1} -2 {input.r2} -o results/{wildcards.sample}/spades_assembly -t {threads} --only-assembler"

rule busco:
    input: "results/{sample}/{sample}_final_polished.fasta"
    output: "results/{sample}/{sample}_busco_report/short_summary.txt"
    threads: 4
    shell:
        """
        busco -i {input} -l xanthomonadales_odb10 -o {wildcards.sample}_busco_report \
        --out_path results/{wildcards.sample} -m genome --offline
        """
